# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(DockerRepo)
    repository: $(imageName)
    command: push
    tags: |
      $(Build.BuildId)