FROM mediasync-api:latest

# Copy files
WORKDIR /root/
RUN rm -r MediaSync-API
ADD . ./MediaSync-API/
WORKDIR /root/MediaSync-API

# Restore and build
RUN dotnet restore
RUN dotnet publish -c Docker
WORKDIR /root/MediaSync-API/bin/Docker/netcoreapp2.2/publish

EXPOSE 8080/tcp 

ENTRYPOINT ["dotnet", "MediaSync.dll"]